TRUNCATE TABLE t_detail_devis RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_demande_status RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_devis RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_demande RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_client RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_type_devis RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_status RESTART IDENTITY CASCADE;